"use client";
import { useEffect, useState } from "react";
import { Building2, Plus, Power, Pencil } from "lucide-react";
import AppShell from "@/components/layout/AppShell";
import Dialog from "@/components/ui/Dialog";
import Alert from "@/components/ui/Alert";
import ModernSelect from "@/components/ui/ModernSelect";
import Spinner from "@/components/ui/Spinner";
import { organizationService, OFFER_LABELS, TYPE_LABELS, type Organization, type OrganizationInput, type OrganizationType, type ServiceOffer } from "@/services/organization-service";
import { userService } from "@/services/user-service";

const EMPTY: OrganizationInput = { name: "", type: "cooperative", offer: "saas_annuel", email: "", phone: "", active: true };
export default function OrganizationsPage() {
  const [items,setItems]=useState<Organization[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [open,setOpen]=useState(false); const [editingId,setEditingId]=useState<string|null>(null); const [form,setForm]=useState<OrganizationInput>(EMPTY); const [saving,setSaving]=useState(false); const [allowed,setAllowed]=useState(false);
  const load=()=>Promise.all([userService.me(),organizationService.list(true)]).then(([profile,orgs])=>{setAllowed(profile.isPlatformAdmin);setItems(orgs);}).catch(e=>setError(e instanceof Error?e.message:"Chargement impossible")).finally(()=>setLoading(false));
  useEffect(()=>{void load();},[]);
  async function save(){ if(!form.name.trim()) return; setSaving(true);setError(null);try{const payload={...form,name:form.name.trim(),email:form.email?.trim()||null,phone:form.phone?.trim()||null}; if(editingId) await organizationService.update(editingId,payload); else await organizationService.create(payload);setOpen(false);setEditingId(null);setForm(EMPTY);await load();}catch(e){setError(e instanceof Error?e.message:"Création impossible");}finally{setSaving(false);} }
  async function toggle(org:Organization){try{const updated=await organizationService.update(org.id,{active:!org.active});setItems(v=>v.map(x=>x.id===org.id?updated:x));}catch(e){setError(e instanceof Error?e.message:"Mise à jour impossible");}}
  return <AppShell title="Organisations" description="Créez et administrez les structures clientes CocoaShield.">{error&&<div className="mb-4"><Alert variant="error">{error}</Alert></div>}{loading?<Spinner label="Chargement des organisations..."/>:!allowed?<Alert variant="error">Cette section est réservée à l’administrateur CocoaShield.</Alert>:<><div className="mb-5 flex justify-end"><button onClick={()=>{setEditingId(null);setForm(EMPTY);setOpen(true);}} className="inline-flex items-center gap-2 rounded-2xl bg-[#244B32] px-4 py-2.5 text-sm font-bold text-white"><Plus className="h-4 w-4"/>Créer une organisation</button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(org=><article key={org.id} className="rounded-3xl border border-[#E2E9DE] bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#EEF5E9] text-[#456A37]"><Building2 className="h-5 w-5"/></div><button onClick={()=>void toggle(org)} className={`rounded-full px-3 py-1 text-xs font-bold ${org.active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}><Power className="mr-1 inline h-3.5 w-3.5"/>{org.active?'Active':'Inactive'}</button></div><h2 className="mt-4 font-bold text-slate-900">{org.name}</h2><p className="mt-1 text-sm text-slate-500">{TYPE_LABELS[org.type]} · {OFFER_LABELS[org.offer]}</p><div className="mt-4 space-y-1 text-xs text-slate-500"><p>{org.email||"Aucun email"}</p><p>{org.phone||"Aucun téléphone"}</p></div><button onClick={()=>{setEditingId(org.id);setForm({name:org.name,type:org.type,offer:org.offer,email:org.email??"",phone:org.phone??"",active:org.active});setOpen(true);}} className="mt-4 inline-flex items-center gap-2 rounded-xl border border-[#DDE6D9] px-3 py-2 text-xs font-bold text-slate-600 hover:bg-[#F7FAF5]"><Pencil className="h-3.5 w-3.5"/>Modifier</button></article>)}</div></>}
  <Dialog open={open} onClose={()=>{setOpen(false);setEditingId(null);}} title={editingId?"Modifier l’organisation":"Créer une organisation"}><div className="space-y-4"><label className="block text-xs font-bold text-slate-600">Nom<input value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} className="mt-1.5 w-full rounded-2xl border border-[#DDE6D9] px-3.5 py-2.5 text-sm"/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">Type<ModernSelect className="mt-1.5" value={form.type} onChange={v=>setForm(x=>({...x,type:v as OrganizationType}))} options={Object.entries(TYPE_LABELS).map(([value,label])=>({value,label}))}/></label><label className="text-xs font-bold text-slate-600">Offre<ModernSelect className="mt-1.5" value={form.offer} onChange={v=>setForm(x=>({...x,offer:v as ServiceOffer}))} options={Object.entries(OFFER_LABELS).map(([value,label])=>({value,label}))}/></label></div><label className="block text-xs font-bold text-slate-600">Email<input type="email" value={form.email??""} onChange={e=>setForm(v=>({...v,email:e.target.value}))} className="mt-1.5 w-full rounded-2xl border border-[#DDE6D9] px-3.5 py-2.5 text-sm"/></label><label className="block text-xs font-bold text-slate-600">Téléphone<input value={form.phone??""} onChange={e=>setForm(v=>({...v,phone:e.target.value}))} className="mt-1.5 w-full rounded-2xl border border-[#DDE6D9] px-3.5 py-2.5 text-sm"/></label><div className="flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="rounded-xl border px-4 py-2 text-sm">Annuler</button><button disabled={saving||!form.name.trim()} onClick={()=>void save()} className="rounded-xl bg-[#244B32] px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving?'Enregistrement...':editingId?'Enregistrer':'Créer'}</button></div></div></Dialog></AppShell>;
}
