export type PlatformSettings = {
  id: string;
  ownerId: string;
  severityLow: number;
  severityModerate: number;
  severityHigh: number;
  severityCritical: number;
  minimumConfidence: number;
  clusteringRadiusM: number;
  minImagesPerZone: number;
  dedupDistanceM: number;
  dedupWindowS: number;
  refreshIntervalConnectedS: number;
  batchRecalcMaxDelayMin: number;
  syncRetryIntervalMin: number;
  offlineTileCacheSizeMb: number;
  historyRetentionMonths: number;
  sessionDurationMinutes: number;
  createdAt: string;
  updatedAt: string;
};

export type DroneProfile = {
  id: string;
  ownerId: string;
  profileId: string;
  manufacturer: string;
  model: string;
  vectorType: "drone_aile_tournante" | "drone_aile_fixe" | "robot_sol" | "mobile";
  supportsRtk: boolean;
  rtkPrecisionCm: number | null;
  rtkFloatPrecisionCm: number | null;
  noCorrectionPrecisionM: number;
  metadataFormat: string;
  latitudeField: string;
  longitudeField: string;
  absoluteAltitudeField: string | null;
  relativeAltitudeField: string | null;
  orientationFields: string;
  timestampField: string;
  rtkStatusField: string | null;
  rtkStatusMapping: string | null;
  nativeMissionExport: string | null;
  active: boolean;
  createdAt: string;
  updatedAt: string;
};

export type DroneProfileInput = {
  profileId: string;
  manufacturer: string;
  model: string;
  vectorType: "drone_aile_tournante" | "drone_aile_fixe" | "robot_sol" | "mobile";
  supportsRtk: boolean;
  rtkPrecisionCm: number | null;
  rtkFloatPrecisionCm: number | null;
  noCorrectionPrecisionM: number;
  metadataFormat: string;
  latitudeField: string;
  longitudeField: string;
  absoluteAltitudeField: string | null;
  relativeAltitudeField: string | null;
  orientationFields: string;
  timestampField: string;
  rtkStatusField: string | null;
  rtkStatusMapping: string | null;
  nativeMissionExport: string | null;
  active?: boolean;
};
